### ISSUE TITLE
Redundant quotes in query parameters interpolation

### ISSUE THREAD

**Issue by yaroslav2k** [haskellari/postgresql-simple#118]
Consider the following code:

```haskell
table_name :: String
table_name = "my_table_name"

createTriggerQuery :: PgSimple.Query
createTriggerQuery = fromString "CREATE TRIGGER my_trigger_name AFTER UPDATE ON ? EXECUTE PROCEDURE proc_name();"

PgSimple.execute conn createTriggerQuery [table_name]
```

This query makes PG backend fail due to the following invalid SQL:

> CREATE TRIGGER my_trigger_name AFTER UPDATE ON 'my_table_name' EXECUTE PROCEDURE proc_name();

because obviously relnames should **not** be quouted in DDL queries.

Are there are fancy ways to resolve this issue while still using `execute` interpolation feature?`` Thanks!

**Comment by phadej** [comment]
`String` is always escaped.

Make a `newtype` to do your own escaping (because relnames should be quoted in general). See `ToField` and https://hackage.haskell.org/package/postgresql-simple-0.6.5.1/docs/Database-PostgreSQL-Simple-ToField.html#t:Action.

That said, it's abusing `postgresql-simple`, and I would advice against.

You cannot prepare "query" like `CREATE TRIGGER my_trigger_name AFTER UPDATE ON ? EXECUTE PROCEDURE proc_name();`, so if `postgresql-simple` changes its approach to use query preparation, what you try to do will break.

**Comment by yaroslav2k** [comment]
> `String` is always escaped.
> 
> Make a `newtype` to do your own escaping (because relnames should be quoted in general). See `ToField` and https://hackage.haskell.org/package/postgresql-simple-0.6.5.1/docs/Database-PostgreSQL-Simple-ToField.html#t:Action.
> 
> That said, it's abusing `postgresql-simple`, and I would advice against.
> 
> You cannot prepare "query" like `CREATE TRIGGER my_trigger_name AFTER UPDATE ON ? EXECUTE PROCEDURE proc_name();`, so if `postgresql-simple` changes its approach to use query preparation, what you try to do will break.

Got it, thanks!
