### ISSUE TITLE
Non-lawful Eq Null instance?

### ISSUE THREAD

**Issue by nomeata** [haskellari/postgresql-simple#78]
I found this code in https://github.com/haskellari/postgresql-simple/blob/master/src/Database/PostgreSQL/Simple/Types.hs#L53-L55:

```
instance Eq Null where
    _ == _ = False
    _ /= _ = False
```
but no rationale for this definition. Why was this definition done? (It has been there since “Initial commit”, so `git blame` does not give any insights.)

**Comment by AntC2** [comment]
> 
> But no hint why `Eq Null` is the way it is.

SQL `Null` is the way it is because SQL has ['three-value logic'](https://en.wikipedia.org/wiki/SQL#Null). (I tend to call it "three-and-a-half value logic"; or not any sort of logic).

Note that unlike haskell's `undefined`; SQL's `Null` is a value you can assign/store in a variable/write out to a database/etc. It's distinct from zero or from a zero-length string. You're supposed to test for it using `... IS [NOT] NULL`, not using equality. (SQL doesn't have anything like a `Maybe` type.)

It's just so darn convenient (= quick-and-dirty) that testing any non-Null value `= Null` returns False (in effect, see below).

> @nomeata And the Haskell == has to match the SQL = here?

I think not. I can see no reason why you'd have `instance Eq Null`.

> Is this a property that is guaranteed in general?

The general rule in SQL is that `Null = <anything>` returns `Null`. But if that result bubbles up to `SELECT ... WHERE ...` statement level, the DB engine has to decide whether to include the row; then a `Null` result means _don't_ select the row; IOW treat the result as if `False`.

I see that PostreSQL repo says:

> -- | A placeholder for the SQL @NULL@ value.

Must be written by somebody who doesn't understand SQL: `Null` is not a "value". It's a 'marker' for the absence of a value (in a field whose type contains 'proper' values like `INT, CHAR, ...`). Hence its behaviour wrt equality testing. I see no reason that repo should even define `data Null = ...`, let alone give an `Eq` instance. SQL has no type `Null`; fields of a genuine type can be marked `NULLABLE`.

**Comment by phadej** [comment]
Thank you, I know what three value logic is. That doesn't explain why `Eq Null` instance was added.
